language: node_js
node_js:
  - "node"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE ChangeNow;'
jdk:
  - oraclejdk8
env:
  global:
    - NODE_ENV: travis
    - secure: TEG8IWpgI9tRIJa88lYw0Il33DCxPPQYPwWd/mcf/ZVZze2DakJY/9EOi3WzFauBiC209uecknGzP28Rbp4d+uFItyrFRa1LWD4+GhUPsvFzdu2NWAAB/djzi01na2WRRkdpP247GQx55x1n5QFnluFGLjiWP8sTSFsoiBnmxSJDqhuGM0hWeEjL5PYIo9ipHx7IR560fqdkrG1OVStnjoaGiEs5JB0qu0qH7wPXkmzzgyDdnTIjdR4x4EJS4qHteWV2qL7G3pZG1I5rA5ZGdht+jIg5x2Lv6il/59hIiD/HBb+NlwzHoSRPx6yoNmII46WWvZiTIGtPiaOveiqRkgbXnZhPtaNq1nfZuvyIUMazNt/GBponlQWxKlUWlRXfED+VmIOMbtTLWf4ZOeFjfIVkgYJ5kAUcz/zvBhC3nQsjSQPl6aoglZHIPlw+Sp5xyKeE215mOkPQ+p4Yz+p86GdKJE1qvJeVUMI8CtJux4YjyzH/gzbOXtBexJa3/gwxQQlGZBPi3Og0rJEHFRWtHofaWrmdd5rcN85fwnhEdN/S8JJiCUg9ugHvq2bCrdQWvSV2I7ZH133wMoHnkVFWurv/Ke0rNHX8STCONm1Xg2KIyQNIjNf/2chXthcEJ1+Rc0cDYtGzOZZJYFBC1CsOHq51VS7H65jR15zMamtouF8=
