swagger: "2.0"
info:
  version: "0.0.1"
  title: ChangeNow API
# during dev, should point to your local machine
host: localhost:8888
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /myfeature:
    x-swagger-router-controller: myfeature
    post:
      description: An awesome feature
      operationId: doSomething
      parameters:
        - name: op1
          in: formData
          description: A param
          required: true
          type: number
        - name: op2
          in: formData
          description: A param
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/doSomethingResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      description: An other awesome feature
      operationId: doSomethingElse
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/doSomethingResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users:
    x-swagger-router-controller: users
    get:
      description: An other awesome feature
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /flipper/enabled:
    x-swagger-router-controller: flipper
    post:
      description: Check if a feature is enabbled for this user
      operationId: isEnabled
      parameters:
        - name: feature
          in: formData
          description: The name of the feature to retrieve
          required: true
          type: string
        - name: actor
          in: formData
          description: user's login
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/isEnabledResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  isEnabledResponse:
    required:
      - enabled
    properties:
      enabled:
        type: boolean
  user:
    required:
      - firstname
      - lastname
      - email
    properties:
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
  doSomethingResponse:
    required:
      - result
    properties:
      result:
        type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
