= ChangeNow Documentation
Alain Hélaïli <helaili@github.com>
:showtitle:
:toc: left
:page-title: ChangeNow Documentation
:page-description: An application using cool concepts such as Documentation-As-Code (Asciidoctor), Feature Toggle (Flipper), Live experiments (Scientist) and MySQL Schema migration (gh-ost)

ChangeNow is an application using several cool concepts such as Documentation-As-Code (http://asciidoctor.org/[Asciidoctor]), Feature Toggle (https://github.com/jnunemaker/flipper[Flipper]), Live experiments (https://github.com/github/scientist[Scientist]) and MySQL Schema migration (https://github.com/github/gh-ost[gh-ost]). Its goal is to demonstrate several modern practices allowing developers to be more agile and productive while maintaining stability.

== What's in the app?

Trying to stay away from the dreaded `hello-world` which leaves you with more question than answers, I have made a point to use a fully functional Node.js application, including tests and continuous integration. This introduced a bit of extra work, but it is something you will face with any real world project. Maybe those are trivial for you, but the lack of documentation found of the web for those challenges make me think it's worth documenting them here:
- AsciiDoc to Jekyll conversion relies on Ruby, but we're in Node.js project,
- Documentation and code should potentially be updated within the same Pull Request, but the AsciiDoc to Jekyll conversion relies on the `gh-pages` branch,
- App was scaffolded with the Vue.js CLI, which by default relies on Chrome for end-to-end tests. This doesn't fly with Travis.
- This list will probably grow

=== Asciidoctor

=== Flipper

=== gh-ost

=== Scientist

=== Travis

=== Other components

Besides all the technology already mentioned, ChnageNow also leverage http://element.eleme.io/#/en-US[Element] for the UI, and http://swagger.io/[Swagger] for the API.

=== Limitations and shortcomings

There's probably a million of them. This project is just a workbench so although it is meant to be realistic, it is far from being perfect. And let's not forget we are writing documentation for the sake of showing how to write documentation!

=== Reference documentation

The following links will help with detailed explanations on Jekyll and AsciiDoc.

* http://jekyllrb.com[Jekyll]
* http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick Reference]
* http://asciidoctor.org[Asciidoctor]
* https://github.com/asciidoctor/jekyll-asciidoc-quickstart[Jekyll AsciiDoc Quickstart]
* https://yermilov.github.io/blog/2017/02/20/using-jekyll-asciidoctor-and-github-pages-for-static-site-creation/[Another Jekyll AsciiDoc tutorial with some extra nuggets]
